### ISSUE TITLE
Update mastertable variable descriptions

### ISSUE THREAD

**Issue by edambo** [brad-cannell/detect_fu_interviews_master_table#17]
- [ ] Include descriptions from the older version of the instruments file. (created separate issue brad-cannell/detect_fu_interviews_public#36)
- [x] Combine the descriptions table for the continuous data and summary table into one for all the datasets.
- [x] Include names and descriptions of free response variables but not summaries and explain why.

**Comment by mbcann01** [comment]
Hi @edambo ,

I'm not sure what this is. Is it done, though?

**Comment by edambo** [comment]
This is essentially the same as issue #36. There are some variables I can't find descriptions for which I asked Sunil about. Otherwise, it should be mostly done as of today. I haven't updated the repository yet but I will at the end of today.

**Comment by mbcann01** [comment]
Thank you, @edambo ! Do you mind closing the issue when it's done?

**Comment by mbcann01** [comment]
Mistake
