### ISSUE TITLE
Change the format of the master table from book to website

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/detect_fu_interviews_master_table#6]
# Overview

I think the screen just looks a little too busy in book format. I want to explore changing it to the [website format](https://quarto.org/docs/websites/). 

# Left off at

2024-01-09
- Made updates to _quarto.yml. 
- I can't test them without the data. I asked Ebie to update the wiki to provide instructions for accessing and storing the data (#7).

**Comment by mbcann01** [comment]
@edambo I changed the website from "book" style to "website" style. I think it looks better. What do you think? If you are good with the changes, you should probably do a fresh pull of the main branch before making any other changes.

**Comment by edambo** [comment]
@brad-cannell Navigation was a little more convenient with the book format since the navigation pane was always on the left, and there was no drop-down menu. But I don't think this is too significant, and it definitely does look better. I will pull the changes.

**Comment by mbcann01** [comment]
Thank you for the feedback!
