### ISSUE TITLE
Add instructions to the wiki for access the data

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/detect_fu_interviews_master_table#7]
# Overview

We need to add instructions for working with the files in this repo to the [wiki](https://github.com/brad-cannell/detect_fu_interviews_master_table/wiki). Specifically, some files about where to locate the data the Quarto files need and how to store them in the repo. This should probably look similar to the [detect_fu_interviews_public wiki](https://github.com/brad-cannell/detect_fu_interviews_public/wiki).

**Comment by mbcann01** [comment]
@edambo , I made some updates to the `_quarto.yml` file in a new branch called `iss-6-website format`. The goal is to change the website from a "book" format to a "website" format (#6). I can't test the changes because I'm not sure how to structure the data to be consistent with your local repo. Do you mind adding some instructions to the wiki that I can follow, please?

**Comment by edambo** [comment]
@mbcann01 I've updated the Wiki with the instructions: [Wiki page](https://github.com/brad-cannell/detect_fu_interviews_master_table/wiki/Data-File-Structure)

**Comment by mbcann01** [comment]
Thank you, @edambo !
